### ISSUE TITLE
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png) test issue

### ISSUE THREAD

**Issue by eru** [eru/dotfiles#1]
test issue

**Comment by DjSoul7** [comment]
![Diploma Campeones (Super Liga)](https://github.com/eru/dotfiles/assets/87060971/65415af5-d442-4d79-876d-97d7e6f13c15)

**Comment by DjSoul7** [comment]
![Diploma Campeones (Super Liga)](https://github.com/eru/dotfiles/assets/87060971/7e98597b-32bf-414e-b43f-dadfbeeb4982)

**Comment by DjSoul7** [comment]
[lobos de venezuela]([https://imgur.com/a/TQpIkgi](url))

**Comment by DjSoul7** [comment]
[](<blockquote class="imgur-embed-pub" lang="en" data-id="a/TQpIkgi" data-context="false" ><a href="//imgur.com/a/TQpIkgi"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>)

**Comment by DjSoul7** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/TQpIkgi" data-context="false" ><a href="//imgur.com/a/TQpIkgi"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by DjSoul7** [comment]
![Diploma Campeones (Super Liga)](https://github.com/eru/dotfiles/assets/87060971/3134b196-011c-44a3-a25f-076e1a05ec38)
